# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.setWindowModality(QtCore.Qt.WindowModal)
        LoginForm.resize(360, 300)
        self.centralwidget = QtWidgets.QWidget(LoginForm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_FullName = QtWidgets.QFrame(self.centralwidget)
        self.frame_FullName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_FullName.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_FullName.setObjectName("frame_FullName")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_FullName)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_FullName)
        self.label_3.setMinimumSize(QtCore.QSize(86, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txt_fullName = QtWidgets.QLineEdit(self.frame_FullName)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_fullName.setFont(font)
        self.txt_fullName.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_fullName.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_fullName.setPlaceholderText("")
        self.txt_fullName.setClearButtonEnabled(True)
        self.txt_fullName.setObjectName("txt_fullName")
        self.horizontalLayout_3.addWidget(self.txt_fullName)
        self.verticalLayout_2.addWidget(self.frame_FullName)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(86, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_psswd = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_psswd.setFont(font)
        self.txt_psswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_psswd.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_psswd.setPlaceholderText("")
        self.txt_psswd.setClearButtonEnabled(True)
        self.txt_psswd.setObjectName("txt_psswd")
        self.horizontalLayout.addWidget(self.txt_psswd)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(7, 0, 7, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Cancel = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_Cancel.setFont(font)
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout_2.addWidget(self.btn_Cancel)
        self.btn_Ok = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_Ok.setFont(font)
        self.btn_Ok.setObjectName("btn_Ok")
        self.horizontalLayout_2.addWidget(self.btn_Ok)
        self.verticalLayout_2.addWidget(self.frame_2)
        LoginForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "KVShop"))
        self.label.setText(_translate("LoginForm", "Авторизация"))
        self.label_3.setText(_translate("LoginForm", "ФИО:"))
        self.label_2.setText(_translate("LoginForm", "Пароль:"))
        self.btn_Cancel.setText(_translate("LoginForm", "Отмена"))
        self.btn_Ok.setText(_translate("LoginForm", "OK"))
