# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_postDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_postDialog(object):
    def setupUi(self, postDialog):
        postDialog.setObjectName("postDialog")
        postDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        postDialog.resize(400, 125)
        postDialog.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(postDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_FullName = QtWidgets.QFrame(postDialog)
        self.frame_FullName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_FullName.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_FullName.setObjectName("frame_FullName")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_FullName)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_FullName)
        self.label_3.setMinimumSize(QtCore.QSize(86, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.txt_postName = QtWidgets.QLineEdit(self.frame_FullName)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_postName.setFont(font)
        self.txt_postName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txt_postName.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_postName.setPlaceholderText("")
        self.txt_postName.setClearButtonEnabled(True)
        self.txt_postName.setObjectName("txt_postName")
        self.verticalLayout.addWidget(self.txt_postName)
        self.verticalLayout_2.addWidget(self.frame_FullName)
        self.buttonBox = QtWidgets.QDialogButtonBox(postDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(postDialog)
        self.buttonBox.rejected.connect(postDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(postDialog)

    def retranslateUi(self, postDialog):
        _translate = QtCore.QCoreApplication.translate
        postDialog.setWindowTitle(_translate("postDialog", "Dialog"))
        self.label_3.setText(_translate("postDialog", "Должность:"))
